vsphere_user       = "YOUR_VSPHERE_SSO_USER_HERE"
vsphere_password   = "YOUR_VSPHERE_PASSWORD_HERE"
vsphere_server     = "vcsa-01.lab"
vsphere_datacenter = "Datacenter"
vsphere_cluster    = "Cluster"
host_hostname = "esxi-01.lab"
host_username = "ESXI_HOST_USERNAME_HERE"
host_password = "ESXI_HOST_PASSWORD_HERE"
