vsphere_user       = "administrator@vsphere.local"
vsphere_password   = "changethispassword"
vsphere_server     = "vcsa-01.lab"
vsphere_datacenter = "Datacenter"
vsphere_cluster    = "Cluster"
host_hostname      = "esxi-01.lab"
host_username      = "root"
host_password      = "changethispassword"
